# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ba6831fd4bcced53a7f912dbb2f3b2ca1aa92855dcebe25dcef7bee681bf0594f2df0283d16c5cc8bc21a6c4b43203c62cf2e3757c2574c0eace879f7df30bb

test:
  secret_key_base: 20596e333e710d00b8b4992fa7e8e819d05892cfc691296fc14965ad7179f3828c62d43ed853534f42502a676bcb8603eff33d9b9f15b221aaee00719c447b80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
